CREATE DATABASE DaSigno;
USE DaSigno;
GO

CREATE TABLE Users(
	UserId INT NOT NULL IDENTITY,
    FirstName VARCHAR(50) NOT NULL,
	SecondName VARCHAR(50) NOT NULL,
	FisrtLastName VARCHAR(50) NOT NULL,
	SecondLastName VARCHAR(50) NOT NULL,
    DateBorn DATE NOT NULL,
	Salary DECIMAL(10,2) NOT NULL,
	RecordDate DATETIME NOT NULL,
	ChangeDate DATETIME NOT NULL,
    PRIMARY KEY(UserId)
);